#! /usr/local/ruby/bin/ruby

desc "Run test"
task :test do
   sh "ruby -I. test/tc_ppt.rb"
   end

desc "Run a specific test, provide a test_name or a /regexp/"
task :t, :test_name do |t, arg|
     test_name = arg [:test_name] || 'test_play'
     sh "ruby -w -Ilib test/tc_ppt.rb --name #{test_name}"
     end
